import Head from "next/head";

const Audio = [];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Record & share audio clips.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="author" content="Muhammed Tijani" />
      </Head>
      <h1>Record and share audio clips using Next.js</h1>
      <main>
        {Audio.map((audio) => (
          <div>
            <h3>{audio.name}</h3>
            <img src={audio.img} alt={audio.name} width={200} height={200} />
            <button>{audio.likes}</button>
          </div>
        ))}
      </main>
    </div>
  );
}
